import os
import re

from langchain_community.vectorstores import FAISS
from retrieval.embeddings import EMBEDDING_MODEL, embeddings


# A new embedding model must never be mixed with vectors generated by an
# older model. Keeping model-specific directories makes the migration safe:
# after switching models, the new index starts empty and documents must be
# re-indexed instead of accidentally loading incompatible vectors.

def _model_slug(model_name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9._-]+", "_", model_name).strip("_")


VECTOR_STORE_PATH = os.path.join("vector_store", _model_slug(EMBEDDING_MODEL))


def create_vector_store(documents):
    """Add documents to the model-specific FAISS index."""
    os.makedirs(VECTOR_STORE_PATH, exist_ok=True)

    index_file = os.path.join(VECTOR_STORE_PATH, "index.faiss")
    if os.path.exists(index_file):
        db = FAISS.load_local(
            VECTOR_STORE_PATH,
            embeddings,
            allow_dangerous_deserialization=True,
        )
        db.add_documents(documents)
    else:
        db = FAISS.from_documents(documents, embeddings)

    db.save_local(VECTOR_STORE_PATH)


def load_vector_store():
    """Load the FAISS index for the currently configured embedding model."""
    index_file = os.path.join(VECTOR_STORE_PATH, "index.faiss")
    if not os.path.exists(index_file):
        raise FileNotFoundError(
            f"No FAISS index exists for embedding model '{EMBEDDING_MODEL}'. "
            "Re-index your documents with the current embedding model first."
        )

    return FAISS.load_local(
        VECTOR_STORE_PATH,
        embeddings,
        allow_dangerous_deserialization=True,
    )
